### ISSUE TITLE
"Couldn't advance to binary doc values for doc" exception for 7.9.2

### ISSUE THREAD

**Issue by ejackson-eb** [alexklibisz/elastiknn#180]
Using the new plug-in for ES 7.9.2 I get this exception when trying to search:

{'error': {'root_cause': [{'type': 'runtime_exception', 'reason': "Couldn't advance to binary doc values for doc with id [404521]"}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'discovery_events_v2', 'node': 'ucbOKdpaRMil3sMIVh17eA', 'reason': {'type': 'runtime_exception', 'reason': "Couldn't advance to binary doc values for doc with id [404521]"}}], 'caused_by': {'type': 'runtime_exception', 'reason': "Couldn't advance to binary doc values for doc with id [404521]", 'caused_by': {'type': 'runtime_exception', 'reason': "Couldn't advance to binary doc values for doc with id [404521]"}}}, 'status': 500}

My search (the value of the vector is omitted) is:

        es_query = {
            "_source": ['id'],
            "size": 20,
            "query": {
                "elastiknn_nearest_neighbors": {
                    "field": "esknn_embedding",
                    "vec": {
                        "values": [...],
                    },
                    "model": "lsh",
                    "similarity": "angular",
                    "candidates": 50
                }
            }
        }

The mapping is:

        "esknn_embedding" : {
          "type" : "elastiknn_dense_float_vector",
          "elastiknn" : {
            "model" : "lsh",
            "similarity" : "angular",
            "dims" : 512,
            "L" : 99,
            "k" : 1
          }
        },

**Comment by ejackson-eb** [comment]
A little of the output from Elasticsearch:

```
Caused by: org.elasticsearch.ElasticsearchException$1: Couldn't advance to binary doc values for doc with id [404521]
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:307) [elasticsearch-7.9.2.jar:7.9.2]
	... 21 more
Caused by: java.lang.RuntimeException: Couldn't advance to binary doc values for doc with id [404521]
	at com.klibisz.elastiknn.query.ExactQuery$StoredVecReader.apply(ExactQuery.scala:53) ~[?:?]
	at com.klibisz.elastiknn.query.HashingQuery$.$anonfun$apply$2(HashingQuery.scala:23) ~[?:?]
	at org.apache.lucene.search.MatchHashesAndScoreQuery$1$2.score(MatchHashesAndScoreQuery.java:168) ~[?:?]
	at org.apache.lucene.search.ConjunctionScorer.score(ConjunctionScorer.java:59) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1.collect(TopScoreDocCollector.java:76) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:242) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:229) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
```

**Comment by alexklibisz** [comment]
That's interesting. I can't think of any obvious reason why that part of the code would have changed for the 7.9.2 build.
Can you tell more about your index setup? At least: how many shards, how many segments, how many total docs?

**Comment by ejackson-eb** [comment]
One shard, 500,000 documents.  This is just an initial test on my work laptop.  I don't know what a segment is.

Maybe I can try to replicate this with a one document index.

**Comment by ejackson-eb** [comment]
Couldn't replicate with a simple one field one document index unfortunately.

25 segments in the original index:
```
index               shard prirep ip        segment generation docs.count docs.deleted     size size.memory committed searchable version compound
discovery_events_v2 0     p      127.0.0.1 _1lp          2077     388877       150231 1012.3mb       20670 true      true       8.6.2   false
discovery_events_v2 0     p      127.0.0.1 _2g5          3173    1359771       984921    6.2gb       42664 true      true       8.6.2   false
discovery_events_v2 0     p      127.0.0.1 _2nt          3449     515047            0  693.1mb       17876 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _3h1          4501     281414            0    839mb       17268 true      true       8.6.2   false
discovery_events_v2 0     p      127.0.0.1 _43t          5321     199234            0  512.5mb       16132 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _4i9          5841      49849            0  128.4mb       13172 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _533          6591      46272            0   99.1mb       13524 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _565          6701     183862            0  525.4mb       16564 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5a1          6841      25803            0   52.2mb       12852 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5dd          6961      22172            0   55.1mb       12964 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5fb          7031      60066            0  107.1mb       13220 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5gp          7081      20324            0     41mb       21228 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5ix          7161      33735            0   78.1mb       12516 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5l5          7241      25158            0   47.1mb       14556 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5mj          7291      97666            0  157.2mb       13204 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5n3          7311      17518            0   48.5mb       16164 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5pb          7391      24012            0     50mb       13268 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5w9          7641       4210            0   19.2mb       14908 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5xd          7681         59            0    324kb       15772 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5xn          7691         44            0  325.9kb       14052 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5y7          7711         46            0  381.5kb       15244 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5yh          7721         74            0  434.8kb       17004 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5ys          7732         92            0  511.9kb       17748 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5z1          7741         93            0  491.3kb       17076 true      true       8.6.2   true
discovery_events_v2 0     p      127.0.0.1 _5z2          7742          2            0   48.1kb       10100 true      true       8.6.2   true
```

**Comment by alexklibisz** [comment]
Thanks for the debugging info.

To clarify: segments are basically to shards as shards are to an index. i.e., an index has one or more shards, and each shard has one or more segments.

One thing you might try next: merge that index into one segment, then re-run? See https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html

That's not a good long-term solution, but it would tell us whether the bug is due to having docs in multiple segments.

I appreciate your patience in helping smooth out these issues :) There's quite a long-tail of use-cases and configurations with Elasticsearch.

**Comment by ejackson-eb** [comment]
One other data point is that if I reindex from the original index (on which I had the exception) to a new index, then the exception goes away.

**Comment by ejackson-eb** [comment]
_forcemerge doesn't seem to do anything.  Returns immediately and the number of segments appears unchanged.

**Comment by alexklibisz** [comment]
> One other data point is that if I reindex from the original index (on which I had the exception) to a new index, then the exception goes away.

Hmm, ok, that makes it sound like there is some issue with how Elastiknn is using Ids when there's > 1 segment.

> _forcemerge doesn't seem to do anything. Returns immediately and the number of segments appears unchanged.

Perhaps try with: `_forcemerge?max_num_segments=1`

Also, I'm not sure if you saw on the 7.9.2 PR, but I made a comment saying the performance is pretty abysmal due to the additional compression that the Lucene project introduced. You might be better off playing around with the latest 7.6.2 version. I'll probably have to add some sort of intermediate caching layer until Lucene gives a way to disable/configure that compression.

**Comment by ejackson-eb** [comment]
Hmm, was just able to reproduce the problem.  To give more context on what I am doing, I first use "reindex" to create a copy of an existing index.  The elastiknn_dense_float_vector field does not exist in the source index.  Then I run a script that makes a bunch of calls to the bulk() API with "update" actions in order to store values (vectors) in the elastiknn_dense_float_vector field.

So, I don't know, maybe some problem with updates.

**Comment by alexklibisz** [comment]
Gotcha. At what point do you update the mapping to include the vector field? If I know that, I should be able to try a repro.

**Comment by ejackson-eb** [comment]
Before the initial reindex, I create the index with the elastiknn_dense_vector field defined in the initial mapping.

In my most recent replication, I saw the problem after updating several thousand documents.

**Comment by alexklibisz** [comment]
All good info. I should have time to look into this tonight.

**Comment by alexklibisz** [comment]
@ejackson-eb When you get a chance, can you try it with the plugin release here: https://github.com/alexklibisz/elastiknn/releases/tag/0.1.0-PRE43-PR184-SNAPSHOT

**Comment by ejackson-eb** [comment]
That plug-in is for 7.6.2, but I have only seen this problem with the plug-in you built for 7.9.2.

**Comment by alexklibisz** [comment]
I see. After I merge this change into master I'll get it out to the 7.9.2 branch as well and it'll publish a snapshot.

**Comment by alexklibisz** [comment]
All of the fixes I've made the past couple weeks, as well as the release for 7.9.2 are out now. Check out the latest version and LMK if you're still having issues with this.

**Comment by ejackson-eb** [comment]
Testing it out.

**Comment by alexklibisz** [comment]
This seems to be resolved based on some email discussion.

**Comment by zhang8473** [comment]
It still happens when I use the plugin 8.12.2.1 version. It has some probability of fetching the docs unsuccessfully.

2024-10-16T08:57:05.104493884Z {"@timestamp":"2024-10-16T08:57:05.104Z", "log.level": "WARN", "message":"path: /myindex/_search, params: {index=myindex}, status: 500", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[myelasticsearch][search][T#18]","log.logger":"rest.suppressed","elasticsearch.cluster.uuid":"iPP6FmgqSLWY6IHEeRy0vA","elasticsearch.node.id":"5DwW84q6SR-LwSLiWxMjYw","elasticsearch.node.name":"myelasticsearch","elasticsearch.cluster.name":"elasticsearch-business-dev-cluster","error.type":"org.elasticsearch.action.search.SearchPhaseExecutionException","error.message":"all shards failed","error.stack_trace":"Failed to execute phase [query], all shards failed; shardFailures {[5DwW84q6SR-LwSLiWxMjYw][myindex][0]: org.elasticsearch.transport.RemoteTransportException: [myelasticsearch][10.42.4.223:9300][indices:data/read/search[phase/query]]\nCaused by: org.elasticsearch.s
earch.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [57403]]\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:73)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:169)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:78)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:717)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:688)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:545)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:73)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:70)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.server@8.12.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: org.elasticsearch.search.internal.ContextIndexSearcher$TimeExceededException\n\tat org.elasticsearch.ser

**Comment by alexklibisz** [comment]
@zhang8473 If it's still an issue, please file a new issue, since this issue is several years old.
