### ISSUE TITLE
Difference exact KNN vs ANN 

### ISSUE THREAD

**Issue by bhushanbrb** [alexklibisz/elastiknn#237]
Tying to know your thought on this difference.
If you look at Row [28] of this notebook 
*Combine keyword and nearest neighbors queries using Elastiknn's approximate query*
with Red it gave weird products vs with exact KNN it gave correct based on color

[multimodal-search-homeimprovement-7.10.2.pdf](https://github.com/alexklibisz/elastiknn/files/5930037/multimodal-search-homeimprovement-7.10.2.pdf)

@alexklibisz thanks for any further pointers on this

**Comment by alexklibisz** [comment]
That's interesting.. did you change anything about the model parameters or vector preprocessing? I see you used a different category of the dataset. It would be helpful to see a diff of your notebook vs. the original.

**Comment by bhushanbrb** [comment]
Hi @alexklibisz thanks for the reply ,  No I did not change any parameters except I used another Amazon dataset from the same place from where you picked shoes , I picked HomeImprovement one.  
>Codewise/Parameter wise no difference
>Datset used http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/meta_Tools_and_Home_Improvement.json.gz
http://snap.stanford.edu/data/amazon/productGraph/image_features/categoryFiles/image_features_Tools_and_Home_Improvement.b
>Issue is exact KNN vs lsh ANN result does not sync

**Comment by alexklibisz** [comment]
I'll try it out locally and see if I can replicate and find any reason for the strange results.

**Comment by alexklibisz** [comment]
Ok -- I think I'm able to replicate the problematic results:

![image](https://user-images.githubusercontent.com/8015228/107159568-f39e1d00-695e-11eb-8f9c-d77243708321.png)

I experimented a bit with different mapping and query settings and I'm pretty sure the reason for these results is this: The vector preprocessing and/or model settings do a poor job of discriminating bad results. So the vector hashes produced by the approximate model are good enough to find the relevant results, but not good enough to filter out the irrelevant results. This is fine for the queries that only look at vectors, since the top vectors get re-scored with the exact score anyways. But when we use a function-score query to combine a `multi_match` query with an elastiknn query, we can't re-score the vectors. There's a note about this [under the "Caveats" section in the docs](https://elastiknn.com/api/#running-nearest-neighbors-query-on-a-filtered-subset-of-documents). So the irrelevant results are never discarded.

I would recommend experimenting with two things:
1. The vector pre-processing -- perhaps we need more than 256 dimensions here.
2. The mapping parameters, specifically `L` and `k`. See the [docs](https://elastiknn.com/api/#angular-lsh-mapping) for notes about these parameters.


 and queries 
2. The specific query is using a function-score query, which doesn't allow us to re-score
