### ISSUE TITLE
elastiknn_unsupported_operation_exception when Kibana tries to access ValueFetcher

### ISSUE THREAD

**Issue by anasben7** [alexklibisz/elastiknn#250]
Hello,
When I create an index pattern in Kibana, and then I go to the discover tab, I got this error:

<img width="668" alt="Screen Shot 2021-04-13 at 14 52 20" src="https://user-images.githubusercontent.com/48560744/114573388-ddb31e00-9c67-11eb-8790-1edc8e6e9be9.png">

The content_embedding field content embedding of type elastiknn_dense_float_vector.
Please help!
Thank you.

**Comment by alexklibisz** [comment]
Ok, so now I finally know the purpose of this method 😄 :
https://github.com/alexklibisz/elastiknn/blob/27fdec11638260e7fde3f01b9763f3eb46acd6dc/elastiknn-plugin/src/main/scala/com/klibisz/elastiknn/mapper/VectorMapper.scala#L81-L82



Can you tell me the exact steps to reproduce?
1. Create an index with an elastiknn_dense_float_vector
2. Use kibana to create an index pattern that includes the index

Is that it?

**Comment by anasben7** [comment]
Hello Alex, 
Yes exactly!

**Comment by alexklibisz** [comment]
Hey @anasben7 can you try the PR/snapshot release here: https://github.com/alexklibisz/elastiknn/releases/tag/7.12.0.0-PR253-SNAPSHOT

I took a very quick first pass - I'm just returning an empty list of values for a vector field (instead of throwing an exception). I'm not 100% certain how Kibana intends to use this functionality, so I'm curious if there is something missing or wrong if it just returns an empty list.

**Comment by alexklibisz** [comment]
I released this fix in 7.12.0.4: https://github.com/alexklibisz/elastiknn/releases/tag/7.12.0.4. Feel free to re-open if this doesn't solve the issue.
